<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><?php echo $this->config['project_name']; ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath; ?>css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath; ?>css/datatables.min.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath; ?>css/dataTables.bootstrap4.min.css"/>
<?php if (isset($view) && $view == 'task/add') { ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath; ?>css/task-add.css"/>
<?php } ?>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     <div class="container">
      <div class="collapse navbar-collapse" id="navbarsExample07">
       <ul class="navbar-nav mr-auto">
        <li class="nav-item">
         <b><a class="nav-link" href="<?php echo $this->basePath; ?>">Main page</a></b>
        </li>
        <li class="nav-item">
         <b><a class="nav-link" href="<?php echo $this->basePath; ?>task/add">Add task</a><b>
        </li>
       </ul>
       <ul class="navbar-nav mr-right">
        <li class="nav-item">
<?php if (isset($this->isAdmin) && $this->isAdmin) { ?>
    <b><a class="nav-link" href="<?php echo $this->basePath; ?>admin/logout">Logout</a></b>
<?php } else { ?>
         <a class="nav-link" href="<?php echo $this->basePath; ?>admin">Login</a>
<?php } ?>
        </li>
       </ul>
      </div>
     </div>
    </nav>

    <div class="container">
      <div class="starter-template">
